function web3(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',fc='.cache.html',_='/',Mb='0596F0278C6980874941F1622BD60465',Ob='181EDD71370AFEBE823DC2B62D4D59D4',Pb='1FBAF2D6DF0A897D689E14DB682968B7',Rb='25AF85E234F71CE3B5CE7533E7D9E976',Tb='2CEFBE49C115AA7C870D9E4F9B96F9D8',Vb='573A142847D3822909AC3E07D1150CC5',ec=':',ob='::',oc='<script defer="defer">web3.onInjectionDone(\'web3\')<\/script>',hb='<script id="',rb='=',$='?',Xb='B1CEC682CA9B47BC4294E61073A88237',tb='Bad handler "',Zb='CA6993A80B7B24CB83F6FFB13AA7FE34',_b='D14D935904BF72F8D3AF1680DC503CC8',bc='DAF30196AC19C7DCAF9B02FCEACCF81E',nc='DOMContentLoaded',dc='EFD4E76362E5A0C07C1CD6FF95CBDBAC',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_web3',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Cb='default',Y='end',$b='es',Nb='es_MX',ac='fr',mc='gwt-cal-apple.css',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',gc='gwt/clean/clean.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',lc='head',Jb='hosted.html?web3',kc='href',xb='iframe',ab='img',Lb='it',yb="javascript:''",hc='link',Ib='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',mb='name',cc='nl',Yb='nn_NO',Ub='no',Qb='pl_PL',zb='position:absolute;width:0;height:0;border:none',ic='rel',db='script',Kb='selectingPermutation',R='startup',jc='stylesheet',Sb='sv',Wb='sv_SE',fb='undefined',Q='web3',eb='web3.nocache.js',nb='web3::';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}web3=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,es:1,es_MX:2,fr:3,it:4,nl:5,nn_NO:6,no:7,pl_PL:8,sv:9,sv_SE:10};web3.onScriptLoad=function(){if(I){q=true;B()}};web3.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Jb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Kb});if(!A()){try{G([Lb],Mb);G([Nb],Ob);G([Cb],Pb);G([Qb],Rb);G([Sb],Tb);G([Ub],Vb);G([Wb],Xb);G([Yb],Zb);G([$b],_b);G([ac],bc);G([cc],dc);K=w[H(Bb)];var M=K.indexOf(ec);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+fc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[gc]){var a=m.createElement(hc);__gwt_stylesLoaded[gc]=a;a.setAttribute(ic,jc);a.setAttribute(kc,s+gc);m.getElementsByTagName(lc)[0].appendChild(a)}if(!__gwt_stylesLoaded[mc]){var a=m.createElement(hc);__gwt_stylesLoaded[mc]=a;a.setAttribute(ic,jc);a.setAttribute(kc,s+mc);m.getElementsByTagName(lc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(nc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(nc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:T});m.write(oc)}
web3();